<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="MSI" failures="1" tests="1" name="PackageTest" time="22.035" errors="0" timestamp="2024-09-24T23:12:14 ICT">
  <testcase classname="test.RunTest" name="test1" time="9.934">
    <failure type="java.lang.AssertionError" message="expected [Signed in successfully1.] but found [Signed in successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Signed in successfully1.] but found [Signed in successfully.]
at test.RunTest.test1(RunTest.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="test.RunTest" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- PackageTest -->
